# Generated by Django 3.1 on 2020-10-26 11:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('message', models.TextField(verbose_name='Текст поздравления')),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/healfy/PycharmProjects/birthday/static/images'), upload_to='photos/', verbose_name='Картинка')),
            ],
        ),
    ]
