# Generated by Django 3.1 on 2020-08-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(verbose_name='Текст поздравления'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(upload_to='photos/', verbose_name='Картинка'),
        ),
    ]
