# Generated by Django 3.1 on 2020-09-04 16:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200827_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/app/static/images'), upload_to='photos/', verbose_name='Картинка'),
        ),
    ]
