# Generated by Django 3.1 on 2020-10-22 11:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200904_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/healfy/PycharmProjects/birthday/static/images'), upload_to='photos/', verbose_name='Картинка'),
        ),
    ]
