# Generated by Django 3.1 on 2020-10-22 17:16

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201022_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текс')),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/home/healfy/PycharmProjects/birthday/static/images'), upload_to='photos/', verbose_name='Картинка')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
            ],
        ),
    ]
